- ros_topic_name: "/attach_link_voxel"
  gz_topic_name: "/attach_link_voxel"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: BIDIRECTIONAL

- ros_topic_name: "/detach_link_voxel"
  gz_topic_name: "/detach_link_voxel"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: BIDIRECTIONAL

- ros_topic_name: "/attach_link1"
  gz_topic_name: "/attach_link1"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: BIDIRECTIONAL

- ros_topic_name: "/detach_link1"
  gz_topic_name: "/detach_link1"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: BIDIRECTIONAL

- ros_topic_name: "/attach_link2"
  gz_topic_name: "/attach_link2"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: BIDIRECTIONAL

- ros_topic_name: "/detach_link2"
  gz_topic_name: "/detach_link2"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: BIDIRECTIONAL


# - ros_topic_name: "/attach_obj_link1"
#   gz_topic_name: "/attach_obj_link1"
#   ros_type_name: "std_msgs/msg/Empty"
#   gz_type_name: "gz.msgs.Empty"
#   direction: BIDIRECTIONAL

# - ros_topic_name: "/attach_obj_link2"
#   gz_topic_name: "/attach_obj_link2"
#   ros_type_name: "std_msgs/msg/Empty"
#   gz_type_name: "gz.msgs.Empty"
#   direction: BIDIRECTIONAL

# - ros_topic_name: "/detach_obj_link1"
#   gz_topic_name: "/detach_obj_link1"
#   ros_type_name: "std_msgs/msg/Empty"
#   gz_type_name: "gz.msgs.Empty"
#   direction: BIDIRECTIONAL

# - ros_topic_name: "/detach_obj_link2"
#   gz_topic_name: "/detach_obj_link2"
#   ros_type_name: "std_msgs/msg/Empty"
#   gz_type_name: "gz.msgs.Empty"
#   direction: BIDIRECTIONAL

- ros_topic_name: "/camera1/image"
  gz_topic_name: "/camera1/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: BIDIRECTIONAL

- ros_topic_name: "/camera1/camera_info"
  gz_topic_name: "/camera1/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: BIDIRECTIONAL

- ros_topic_name: "/camera2/image"
  gz_topic_name: "/camera2/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: BIDIRECTIONAL

- ros_topic_name: "/camera2/camera_info"
  gz_topic_name: "/camera2/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: BIDIRECTIONAL

- ros_topic_name: "/robot/contact1"
  gz_topic_name: "/robot/contact1"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: BIDIRECTIONAL  

- ros_topic_name: "/robot/contact2"
  gz_topic_name: "/robot/contact2"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: BIDIRECTIONAL  

- ros_topic_name: "/robot/imu1"
  gz_topic_name: "/robot/imu1"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: BIDIRECTIONAL  

- ros_topic_name: "/robot/imu2"
  gz_topic_name: "/robot/imu2"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: BIDIRECTIONAL  

  
