# ATTACH/DETACH to base
- ros_topic_name: "/attach_link1"
  gz_topic_name: "/attach_link1"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: BIDIRECTIONAL

- ros_topic_name: "/detach_link1"
  gz_topic_name: "/detach_link1"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: BIDIRECTIONAL

- ros_topic_name: "/attach_link2"
  gz_topic_name: "/attach_link2"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: BIDIRECTIONAL

- ros_topic_name: "/detach_link2"
  gz_topic_name: "/detach_link2"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: BIDIRECTIONAL

# DETACH all objects topics
- ros_topic_name: "/detach1_objects"
  gz_topic_name: "/detach1_objects"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: BIDIRECTIONAL

- ros_topic_name: "/detach2_objects"
  gz_topic_name: "/detach2_objects"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: BIDIRECTIONAL

# CAMERAS sensor
- ros_topic_name: "/camera1/image"
  gz_topic_name: "/camera1/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: BIDIRECTIONAL

- ros_topic_name: "/camera1/camera_info"
  gz_topic_name: "/camera1/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: BIDIRECTIONAL

- ros_topic_name: "/camera2/image"
  gz_topic_name: "/camera2/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: BIDIRECTIONAL

- ros_topic_name: "/camera2/camera_info"
  gz_topic_name: "/camera2/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: BIDIRECTIONAL

# CONTACT sensor
- ros_topic_name: "/robot/contact1"
  gz_topic_name: "/robot/contact1"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: BIDIRECTIONAL  

- ros_topic_name: "/robot/contact2"
  gz_topic_name: "/robot/contact2"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: BIDIRECTIONAL  

# IMU
- ros_topic_name: "/robot/imu1"
  gz_topic_name: "/robot/imu1"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: BIDIRECTIONAL  

- ros_topic_name: "/robot/imu2"
  gz_topic_name: "/robot/imu2"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: BIDIRECTIONAL  
  
# Object poses
# - ros_topic_name: "/model/part1/pose"
#   gz_topic_name: "/model/part1/pose"
#   ros_type_name: "geometry_msgs/msg/Pose"
#   gz_type_name: "gz.msgs.Pose"
#   direction: GZ_TO_ROS

- topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
