controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

position_controller1:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints: 
      - rev0_1
    command_interface: position

position_controller2:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints: 
      - rev2_3
    command_interface: position
  
position_controller3:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints: 
      - rev5_6
    command_interface: position

position_controller4:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints: 
      - rev8_9
    command_interface: position

position_controller5:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints: 
      - rev10_11
    command_interface: position
